version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/httpstub
    steps:
      - run: |
          mkdir -p $HOME/bin
          echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: |
          curl -L -o /tmp/ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar -C /tmp -zxf /tmp/ghr.tar.gz
          mv /tmp/ghr_v0.13.0_linux_amd64/ghr $HOME/bin/ghr
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build.gradle" }}
          - v2-dependencies-
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v2-dependencies-{{ checksum "build.gradle" }}
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            ghr -u int128 -r httpstub -n "$CIRCLE_TAG" -b "Released on $(date +%Y-%m-%d)" "$CIRCLE_TAG" build/libs/httpstub.jar
          fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: open-source
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
