#TODO: remove
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/httpstub
    steps:
      - run: "true"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: dummy
            tags:
              only: dummy
