name: build-image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  latest:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      tag: ghcr.io/int128/httpstub:latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: docker build . --tag $tag --cache-from $tag
      - run: docker push $tag
        if: github.ref == 'refs/heads/master'
