name: docker

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile
      - Makefile
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile
      - Makefile

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/buildx
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make docker-build
        if: github.event_name == 'pull_request'
      - run: make docker-build-push
        if: github.event_name == 'push'
