name: docker

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
      - if: startswith(github.ref, 'refs/tags/')
        run: echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
      - if: startswith(github.ref, 'refs/tags/') == false
        run: echo tag=latest >> "$GITHUB_ENV"
      - run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/buildx-cache" \
            --cache-to "type=local,dest=/tmp/buildx-cache" \
            --output "type=image,push=false" \
            --tag "$DOCKER_REPOSITORY:$tag" \
            .
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - if: github.event_name == 'push'
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/buildx-cache" \
            --output "type=image,push=true" \
            --tag "$DOCKER_REPOSITORY:$tag" \
            .
