name: docker

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: ([[ $GITHUB_REF == refs/tags/* ]] && echo "tag=${GITHUB_REF##*/}" || echo tag=latest) >> "$GITHUB_ENV"
      - run: docker build . --tag "$DOCKER_REPOSITORY:$tag" --cache-from "$DOCKER_REPOSITORY:latest" --build-arg BUILDKIT_INLINE_CACHE=1
      - run: docker push "$DOCKER_REPOSITORY:$tag"
        if: github.event_name == 'push'
