name: docker

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile

jobs:
  build-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - run: .github/docker-build-config.sh
        id: docker-build-config
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: ${{ steps.docker-build-config.outputs.push }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.docker-build-config.outputs.tag }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildkit-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildkit-cache,mode=max
